import React from 'react'
import "./terms_main.scss"

export default function Terms_main() {
  return (
    <div className='terms_main'>
        <div className='content'>
          <div>
            <figure>Last Revised on July 21, 2022</figure>
            <figcaption>These Terms of Service (these "Terms") govern your use of the website <a href='https://govern.staratlas.com' target="_blank" rel="noreferrer">https://govern.staratlas.com</a> (the "Website") and all content and functionalities accessible via the Website (collectively, the "Services") operated by the Star Atlas Foundation ("Star Atlas Foundation"), a Cayman Islands foundation limited by guarantee and without share capital, on behalf of the decentralized autonomous organization that helps govern the Star Atlas metaverse (the "Star Atlas DAO").</figcaption>
          </div>
          <section>
            <ol>
              <li><span>Description of Services.</span>
                The Services act as an interface through which eligible users can vote on specific aspects put forth by the Star Atlas DAO ("Voting Rights"). The Voting Rights are set forth on the Website. The Star Atlas Foundation (itself or through a service provider) acts on behalf of and for the benefit of the Star Atlas DAO in maintaining the Website as a front-end access to the decentralized digital ecosystem utilizing the POLIS and ATLAS tokens on the Solana blockchain. For the avoidance of doubt, the Star Atlas Foundation does not control your or any other user‘ Voting Rights, and does not control the Solana blockchain or the protocols that govern the Solana blockchain (collectively, the "Solana Network") and cannot control activity and data on the Solana Network, the validation of transactions on the Solana Network, or use of the Solana Network. The Solana Network contains open-source protocols that are maintained and processed by validators across the globe.</li>
              <li><span>Agreement to Terms.</span>Please read these Terms carefully, as they include important information about your legal rights. By accessing and/or using the Services, you are agreeing to these Terms. If you do not understand or agree to these Terms, please do not use the Services.</li>
              <li><span>Privacy Policy.</span>Our Privacy Policy describes how we handle the information you provide to us when you use the Services. For an explanation of our privacy practices, please visit our Privacy Policy located at <a href='https://govern.staratlas.com' target="_blank" rel="noreferrer">https://govern.staratlas.com/privacy-policy.</a></li>
              <li><span>Eligibility.</span>You must be 18 years or older and capable of forming a binding contract with the Star Atlas Foundation, and not otherwise barred from using the Services under applicable law. For purposes of these Terms, "you" and "your" means you as the user of the Services. If you use the Services on behalf of a company or other entity then “you” includes you and that entity, and you represent and warrant that (a) you are an authorized representative of the entity with the authority to bind the entity to these Terms, and (b) you agree to these Terms on the entity‘ behalf.</li>
              <li><span>Feedback.</span>We welcome feedback, bug reports, comments, and suggestions for improvements to the Services, but please do not send suggestions for creative ideas, designs, pitch portfolios, or other similar such materials ("Unsolicited Ideas"). We may currently be developing, have developed, or in the future will develop ideas or materials internally or receive ideas or materials from other parties that may purely by coincidence be similar to Unsolicited Ideas. If you ignore this policy and send us your Unsolicited Ideas anyway, you grant us a non-exclusive, worldwide, perpetual, irrevocable, fully-paid, royalty-free, sublicensable, and transferable license under any and all intellectual property or other rights that you own or control to use, copy, modify, create derivative works based upon, make, have made, sell, offer for sale, import, and otherwise exploit in any manner or medium whatsoever known now or in the future your Unsolicited Ideas for any purpose, without compensation to you.</li>
              <li><span>Star Atlas Foundation‘ Intellectual Property.</span> We may make available through the Services content that is subject to intellectual property rights. We, our licensors, or third parties who otherwise own the intellectual property rights retain all rights to that content.</li>
              <li><span>Your Content License Grant.</span>In connection with your use of the Services, you may be able to post, upload, or submit content to be made available through the Services ("Your Content"), such as user profiles, comments, user avatars, guild names, sound files, images, music files, game assets, and other user generated content. In order to operate the Services, we must obtain from you certain license rights in Your Content so that actions we take in operating the Services are not considered legal violations. Accordingly, by using the Services and uploading Your Content, you grant us a license to access, use, host, cache, store, reproduce, transmit, display, publish, distribute, and modify (for technical purposes, e.g., making sure content is viewable on smartphones as well as computers and other devices) Your Content to be able to operate and provide the Services. You agree that these rights and licenses are royalty free, transferable, sub-licensable, worldwide, and irrevocable (for so long as Your Content is stored with us), and include a right for us to make Your Content available to, and pass these rights along to, others with whom we have contractual relationships related to the provision of the Services, solely for the purpose of providing such Services, and to otherwise permit access to or disclose Your Content to third parties if we determine such access is necessary to comply with our legal obligations. As part of the foregoing license grant you agree that the other users of the Services shall have the right to comment on and/or tag Your Content and/or to use, publish, display, modify, or include a copy of Your Content as part of their own use of the Services; except that the foregoing shall not apply to any of Your Content that you post privately for non-public display on the Services. By posting or submitting Your Content through the Services, you represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power, and/or authority necessary to grant the rights granted herein for Your Content. You agree that Your Content will not contain material subject to copyright or other proprietary rights, unless you have the necessary permission or are otherwise legally entitled to post the material and to grant us the license described above.</li>
              <li><span>General Prohibitions and Star Atlas Foundation‘ Enforcement Rights.</span>You agree not to do any of the following: <ol>
                <li>Use, display, mirror, or frame the Services or any individual element within the Services, the name of the Services, any trademark, logo, or other proprietary information on the Services (whether owned by Star Atlas Foundation or licensed from a third party), or the layout or design of any page or form contained on a page, without the Star Atlas Foundation‘ express written consent;</li>
                <li>Access, tamper with, or use non-public areas of the Services, Star Atlas Foundation‘ computer systems, or the technical delivery systems of Star Atlas Foundation‘ providers;</li>
                <li>Attempt to probe, scan, or test the vulnerability of any Star Atlas Foundation‘ (or its providers‘) system or network or breach any security or authentication measures;</li>
                <li>Avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by the Star Atlas Foundation or any of Star Atlas Foundation‘ providers or any other third party (including another user) to protect the Services or ensure only eligible voters can exercise Voting Rights via the Services;</li>
                <li>Attempt to access or search the Services or download content from the Services using any engine, software, tool, agent, device, or mechanism (including spiders, robots, crawlers, data mining tools, or the like) other than the software and/or search agents provided by the Star Atlas Foundation or other generally available third-party web browsers;</li>
                <li>Use the Services, or any portion thereof, for any commercial purpose or for the benefit of any third party or in any manner not permitted by these Terms;</li>
                <li>Attempt to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Services;</li>
                <li>use the Services for illegal, harassing, unethical, or disruptive purposes, including engaging in any conduct intended to disrupt or diminish the experience for other users or disrupt operation of the Services in any way, including: (i) disrupting or assisting in the disruption of any computer used to support the Services, or (ii) harassment, “griefing,” abusive behavior or chat, conduct intended to unreasonably undermine or disrupt the experiences of others, deliberate inactivity, or disconnecting;</li>
                <li>use the Services in such a way as to infringe the privacy, intellectual property rights, or other rights of third parties;</li>
                <li>Interfere with, or attempt to interfere with, the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Services;</li>
                <li>Impersonate or misrepresent your affiliation with any person or entity;</li>
                <li>Violate any applicable law or regulation; or</li>
                <li>Encourage or enable any other individual to do any of the foregoing.</li>
              </ol>The Star Atlas Foundation is not obligated to monitor access to or use of the Services or to review or edit any content. However, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider it objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.</li>
              <li><span>Termination.</span>We may suspend or terminate your access to and use of the Services at our sole discretion at any time and without notice to you.</li>
              <li><span>Geographic Restrictions.</span>The Star Atlas Foundation is based in the Cayman Islands. We make no claims that the Services or any of their content is accessible or appropriate outside of the Cayman Islands. Access to the Services may not be legal by certain persons or in certain countries. If you access the Services from outside the Cayman Islands, you do so on your own initiative and are responsible for compliance with local laws.</li>
              <li><span>Warranty Disclaimers.</span><ol>
                <li>THE SERVICES ARE PROVIDED “AS IS,” WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE EXPLICITLY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. We make no warranty that the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness, or reliability of any information or content on the Services. Any reliance you place on such information or content is strictly at your own risk.</li>
                <li><span>Assumption of Risks.</span>To the extent the Services allow you to interact with the Solana Network or any other blockchain (including the protocols that govern such blockchain) or any third-party websites, cryptocurrency wallets or other resources (each, a "Third Party Resource"), you understand that your use of each Third Party Resource is entirely at your own risk. Each Third Party Resource is available on an “as is” basis without warranties of any kind, either express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, quiet enjoyment, and non-infringement. You assume all risks associated with using each Third Party Resource, and digital assets and decentralized systems generally, including, but not limited to, that digital assets are highly volatile; you may not have ready access to assets; changes to regulatory regimes governing blockchain technologies may materially adversely affect the development of the Services and therefore the potential utility of your tokens or assets; and you may lose some or all of your tokens or other assets. You agree that you will have no recourse against the Star Atlas Foundation or anyone else for any losses due to the use of any Third Party Resource. For example, these losses may arise from or relate to: (i) lost funds; (ii) server failure or data loss; (iii) corrupted cryptocurrency wallet files; (iv) unauthorized access; (v) bugs, errors, mistakes, or inaccuracies; (vi) third-party activities, including by governments and regulators; or (vii) other unanticipated risks.</li>
              </ol></li>
              <li><span>Indemnity.</span>You will indemnify and hold the Star Atlas Foundation and its supervisors, officers, directors, employees, and agents, harmless from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (a) your access to or use of the Services, or (b) your violation of these Terms.</li>
              <li><span>Limitation of Liability.</span>
              <ol>
                <li>TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER THE STAR ATLAS FOUNDATION NOR ITS SERVICE PROVIDERS INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE, SYSTEM FAILURE, OR THE COST OF SUBSTITUTE SERVICES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT THE STAR ATLAS FOUNDATION OR ITS SERVICE PROVIDERS HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.</li>
                <li>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE STAR ATLAS FOUNDATION‘ TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES EXCEED ONE HUNDRED U.S. DOLLARS ($100).</li>
                <li>THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN THE STAR ATLAS FOUNDATION AND YOU.</li>
                </ol></li>
              <li><span>Governing Law and Forum Choice.</span>These Terms and any action related thereto will be governed by the laws of the Cayman Islands, without regard to its conflict of laws provisions. The parties expressly consent to personal and exclusive jurisdiction in the courts located in the Cayman Islands, and you and the Star Atlas Foundation each waive any objection to jurisdiction and venue in such courts. You agree that in the event of any dispute between you and the Star Atlas Foundation, you will first contact the Star Atlas Foundation and make a good faith sustained effort to resolve the dispute before resorting to more formal means of resolution.</li>
              <li><span>General Terms.</span><ol>
                <li><span>Reservation of Rights.</span>The Star Atlas Foundation and its licensors exclusively own all right, title, and interest in and to the Services, including all associated intellectual property rights. You acknowledge that the Services are protected by copyright, trademark, and other laws of the Cayman Islands and other jurisdictions. You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Services.</li>
                <li><span>Entire Agreement.</span>These Terms constitute the entire and exclusive understanding and agreement between the Star Atlas Foundation and you regarding the Services, and these Terms supersede and replace all prior oral or written understandings or agreements between the Star Atlas Foundation and you regarding the Services. If any provision of these Terms is held invalid or unenforceable by a court of competent jurisdiction, that provision will be enforced to the maximum extent permissible and the other provisions of these Terms will remain in full force and effect. Except where provided by applicable law in your jurisdiction, you may not assign or transfer these Terms, by operation of law or otherwise, without the Star Atlas Foundation‘ prior written consent. Any attempt by you to assign or transfer these Terms absent our consent or your statutory right without such consent will be null. The Star Atlas Foundation may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors, and permitted assigns.</li>
                <li><span>Other Terms.</span>These Terms govern your use of the Services and only these Services. Other terms and conditions may apply to your use of other content, functionality, products, or services that may relate directly or indirectly to the Star Atlas game or metaverse, such as those provided by ATMTA, Inc. via the website <a href='https://govern.staratlas.com' target="_blank" rel="noreferrer">https://staratlas.com</a> (which are subject to the Terms of Service located at <a href='https://govern.staratlas.com' target="_blank" rel="noreferrer">https://staratlas.com/terms-of-service</a> ) or those provided by a third-party digital asset wallet provider.</li>
                <li><span>Notices.</span>Any notices or other communications provided by the Star Atlas Foundation under these Terms will be given by posting to the Services.</li>
                <li><span>Waiver of Rights.</span>The Star Atlas Foundation‘ failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of the Star Atlas Foundation. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.</li>
                <li><span>Taxes.</span>You are solely responsible to pay any and all sales, use, value-added, and other taxes, duties, and assessments (except taxes on our net income) now or hereafter claimed or imposed by any governmental authority associated with your use of the Services. Neither these Terms nor any other communication from the Star Atlas Foundation constitutes tax advice, and users are solely responsible for determining what, if any, taxes apply to their interaction with the Services.</li>
                <li><span>Force Majeure.</span>We will not be liable or responsible to you, nor be deemed to have defaulted under or breached these Terms, for any failure or delay in fulfilling or performing any of our obligations under these Terms or in operating the Services, when and to the extent such failure or delay is caused by or results from any events beyond our ability to control, including flood, fire, earthquake, epidemics, pandemics, quarantine restrictions, tsunami, explosion, war, invasion, hostilities (whether war is declared or not), terrorist threats or acts, riot or other civil unrest, government order, law, or action, embargoes or blockades, strikes, labor stoppages or slowdowns or other industrial disturbances, shortage of adequate or suitable Internet connectivity, telecommunication breakdown, shortage of adequate power or electricity, and other similar events beyond our control.</li>
                <li><span>Updating These Terms.</span>We may modify these Terms from time to time in which case we will update the “Last Revised On” date at the top of these Terms. If we make changes that are material, we will use reasonable efforts to attempt to notify you. However, it is your sole responsibility to review these Terms from time to time to view any such changes. The updated Terms will be effective as of the time of posting, or such later date as may be specified in the updated Terms. Your continued access or use of the Services after the modifications have become effective will be deemed your acceptance of the modified Terms.</li>
                <li><span>Miscellaneous.</span>If any provision of these Terms shall be unlawful, void, or for any reason unenforceable, then that provision shall be deemed severable from these Terms and shall not affect the validity and enforceability of any remaining provisions. These Terms and the licenses granted hereunder may be assigned by the Star Atlas Foundation but may not be assigned by you without the prior express written consent of the Star Atlas Foundation. No waiver by either party of any breach or default hereunder shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used herein are for reference only and shall not be read to have any legal effect.</li>
                </ol></li>
              <li><span>Contact Information.</span> If you have any questions about these Terms or the Services, please contact the Star Atlas Foundation at <a href='https://govern.staratlas.com' target="_blank" rel="noreferrer">contact@govern.staratlas.com.</a> </li>
            </ol>
          </section>
        </div>
      </div>
  )
}
